name: green_rewards_adminv1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  mailer: ^6.1.0
  http: ^1.4.0
  random_string: ^2.3.1  # Replaced uuid with random_string
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true